# Código que chama as tarefas de instalação
# e configuração do wordpress localizados em roles
---
- hosts: wordpress
  remote_user: aluno
  become: yes
  roles:
  - server
  - php
  - mysql
  - wordpress
