---

- hosts: wordpress

  remote_user: aluno

  become: yes

  tasks:

   - name: "Executa o container MySQL"

     docker_container:

       name: dbferraz2

       image: mysql:5.6

       env:

        MYSQL_ROOT_PASSWORD: P@ssw0rd

   - name: "Executa o container WordPress"

     docker_container:

       name: siteferraz2

       image: wordpress

   - name: "Executa o container WordPress"

     docker_container:

       name: siteferraz2

       image: wordpress
       links:

        - "dbferraz2:mysql"

       ports:

        - "8090:80"

