---
- name: Atualiza o cache apt de nosso servidor
  apt: update_cache=yes cache_valid_time=3600
 
- name: Instala os pacotes necessarios
  apt: name={{ item }} state=present
  with_items:
  - apache2
  - mysql-server
  - python-mysqldb
  - php-mysql
  - php
  - libapache2-mod-php
  - php-mcrypt
